# Generated by Django 4.1.7 on 2023-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='AAAAAA', max_length=8, unique=True),
        ),
    ]
